name: pixeltales-prod

services:
  frontend:
    container_name: pixeltales-frontend-prod
    image: pixeltales-frontend-prod
    build:
      context: ./frontend
      target: production-runtime
    ports:
      - '${FRONTEND_PORT:-80}:80'
    environment:
      - DOCKER_ENV=true
      - VITE_BACKEND_URL=http://backend:${BACKEND_PORT:-8000}
    depends_on:
      - backend
    networks:
      - app-network
    env_file: .env.production

  backend:
    container_name: pixeltales-backend-prod
    image: pixeltales-backend-prod
    build:
      context: ./backend
      target: production
    working_dir: /workspace
    ports:
      - '${BACKEND_PORT:-8000}:8000'
    volumes:
      # Only persistent storage for SQLite database
      - ./data/sqlite:/data/sqlite:rw
    environment:
      - ENV=production
      - FRONTEND_PORT=${FRONTEND_PORT:-80}
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-["http://localhost:${FRONTEND_PORT:-80}", "http://localhost", "http://127.0.0.1:${FRONTEND_PORT:-80}", "http://127.0.0.1"]}
      - DB_TYPE=${DB_TYPE:-sqlite}
      - SQLITE_URL=${SQLITE_URL:-sqlite+aiosqlite:////data/sqlite/pixeltales.db}
    env_file: .env.production
    networks:
      - app-network

networks:
  app-network:
    name: pixeltales-network-prod
    driver: bridge
