import { Inject, Injectable, Logger } from '@nestjs/common';
import { Metric } from '@pixeltales/contracts';
import { metrics } from '@pixeltales/database'; // Import the metrics schema
import { DRIZZLE_INSTANCE, DatabaseSchema } from '../../../db/drizzle.provider'; // Corrected relative path again
import { IMetricsAdapter } from './metrics.adapter.interface';

/**
 * Adapter for writing metrics to the SQLite `metrics` table,
 * simulating a Time Series Database interface.
 */
@Injectable()
export class TimeSeriesAdapter implements IMetricsAdapter {
  private readonly logger = new Logger(TimeSeriesAdapter.name);

  constructor(@Inject(DRIZZLE_INSTANCE) private readonly db: DatabaseSchema) {}

  async writePoint(metric: Metric): Promise<void> {
    this.logger.verbose(`Writing metric point to SQLite: ${metric.name}`);
    if (!this.db) {
      this.logger.error('Drizzle instance is not available in TimeSeriesAdapter.writePoint');
      return; // Or throw an error
    }
    try {
      await this.db.insert(metrics).values({
        // id will be generated by defaultFn
        name: metric.name,
        timestamp: new Date(metric.timestamp), // Drizzle expects Date object for timestamp_ms
        tags: metric.tags,
        fields: metric.fields,
      });
    } catch (error) {
      if (error instanceof Error) {
        this.logger.error(
          `Failed to write metric point: ${metric.name} - ${error.message}`,
          error.stack,
        );
      } else {
        this.logger.error(`Failed to write metric point: ${metric.name} - Unknown error`, error);
      }
      // Decide if we should throw or just log
      // throw error; // Re-throw if necessary
    }
  }

  async batchInsert(metricsToInsert: Metric[]): Promise<void> {
    if (metricsToInsert.length === 0) return;
    this.logger.verbose(`Batch writing ${metricsToInsert.length} metrics to SQLite.`);

    if (!this.db) {
      this.logger.error('Drizzle instance is not available in TimeSeriesAdapter.batchInsert');
      return; // Or throw an error
    }

    const values = metricsToInsert.map((metric) => ({
      name: metric.name,
      timestamp: new Date(metric.timestamp), // Drizzle expects Date object
      tags: metric.tags,
      fields: metric.fields,
    }));

    try {
      // Drizzle handles batch inserts efficiently for supported drivers (including better-sqlite3)
      await this.db.insert(metrics).values(values);
    } catch (error) {
      if (error instanceof Error) {
        this.logger.error(
          `Failed to batch write ${metricsToInsert.length} metrics - ${error.message}`,
          error.stack,
        );
      } else {
        this.logger.error(
          `Failed to batch write ${metricsToInsert.length} metrics - Unknown error`,
          error,
        );
      }
      // Decide on error handling: throw, or try individual inserts?
      // Fallback to individual inserts (less efficient)
      /*
      this.logger.warn('Batch insert failed, attempting individual inserts...');
      for (const metric of metricsToInsert) {
        await this.writePoint(metric).catch(err => {
          this.logger.error(`Individual metric insert failed for ${metric.name}`, err);
        });
      }
      */
      // Or re-throw:
      // throw error;
    }
  }
}
