"""initial schema

Revision ID: be0f2d68ab8e
Revises:
Create Date: 2026-04-24 03:29:35.262193

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be0f2d68ab8e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scene_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("votes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scene_configs_created_at"), "scene_configs", ["created_at"], unique=False
    )
    op.create_table(
        "scenes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["config_id"], ["scene_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scenes_created_at"), "scenes", ["created_at"], unique=False)
    op.create_table(
        "scene_state_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["config_id"], ["scene_configs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scene_state_snapshots_timestamp"),
        "scene_state_snapshots",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scene_state_snapshots_timestamp"), table_name="scene_state_snapshots")
    op.drop_table("scene_state_snapshots")
    op.drop_index(op.f("ix_scenes_created_at"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_scene_configs_created_at"), table_name="scene_configs")
    op.drop_table("scene_configs")
    # ### end Alembic commands ###
