import { index, integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';
import { uuid } from '../../uuid'; // Import uuid helper

// TODO: Define agent table if needed or confirm agentId source

export const hypothesisStatusEnum = [
  'proposed',
  'testing',
  'confirmed',
  'refuted',
  'superseded',
] as const;
export type HypothesisStatus = (typeof hypothesisStatusEnum)[number];

/**
 * Stores hypotheses generated by the agent's Curiosity System.
 * Represents testable assumptions about the world or other agents.
 */
export const hypotheses = sqliteTable(
  'hypotheses',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => uuid()), // Use text UUID
    agentId: text('agent_id').notNull(), // Agent who generated the hypothesis
    description: text('description').notNull(), // Textual description of the hypothesis
    triggeringObservationId: text('triggering_observation_id'), // Use text FK (if linking to episodic)
    // Store status as text
    status: text('status', { enum: hypothesisStatusEnum }).notNull().default('proposed'),
    confidence: real('confidence').notNull().default(0.5), // Agent's initial confidence
    // Store tags as text, let Drizzle parse based on $type
    tags: text('tags', { mode: 'json' }).$type<string[]>(),
    // Store timestamps as integers (Unix epoch milliseconds)
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull().defaultNow(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull().defaultNow(),
  },
  (table) => [
    index('hypothesis_agent_id_idx').on(table.agentId),
    index('hypothesis_status_idx').on(table.status),
    // SQLite FKs are typically enabled via PRAGMA but Drizzle handles the definition.
    // We can still define the relation conceptually.
    // triggerObsFk: foreignKey({
    //   columns: [table.triggeringObservationId],
    //   foreignColumns: [episodicMemoryEntries.id] // Assuming episodicMemoryEntries is defined elsewhere
    // }).onDelete('set null'),
  ],
);

// Relation defined in experiments.schema.ts
