import { z } from 'zod';

/**
 * Defines the structure for a reflection report generated by the agent.
 * Captures insights derived from reviewing recent experiences.
 */
export const ReflectionReportSchema = z.object({
  reportId: z.string().uuid().describe('Unique identifier for the reflection report.'),
  timestamp: z.number().int().positive().describe('Timestamp when the reflection occurred.'),
  trigger: z
    .string()
    .describe('Reason why reflection was initiated (e.g., idle, periodic, explicit_goal).'),
  processedObservationIds: z
    .array(z.string().uuid())
    .optional()
    .describe('IDs of observations considered during this reflection.'),
  insights: z
    .array(
      z.object({
        type: z
          .enum(['self', 'world', 'social', 'goal', 'learning', 'other'])
          .describe('Category of the insight.'),
        content: z.string().describe('The textual content of the insight derived.'),
        confidence: z.number().min(0).max(1).describe('Agent-assessed confidence in the insight.'),
        supportingEvidenceIds: z
          .array(z.string().uuid())
          .optional()
          .describe('IDs of facts/observations supporting this insight.'),
      }),
    )
    .describe('List of insights generated during reflection.'),
  // Optional fields for specific updates derived from insights
  potentialSelfModelUpdates: z
    .record(z.string(), z.any())
    .optional()
    .describe('Suggested updates to the agent self-model based on reflection.'),
  potentialOntologyUpdates: z
    .array(
      z.object({
        /* Define structure based on Ontology schemas */
      }),
    )
    .optional()
    .describe('Suggested updates to the ontology based on reflection.'),
  newGoalsSuggested: z
    .array(z.string())
    .optional()
    .describe('New short-term goals suggested by the reflection process.'),
});

export type ReflectionReport = z.infer<typeof ReflectionReportSchema>;
